spring:
  application:
    name: sangchu-spring
  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: 3.36.91.181
      port: 6379
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      username : ${REDIS_USERNAME}
#      pw: ${REDIS_PASSWORD}

  datasource:
#    jdbc-url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    jdbc-url: jdbc:postgresql://j10b206.p.ssafy.io:5432/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true

  thymeleaf:
    cache: false

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${SERVER_PORT} # jenkins와 8080 포트 충돌 방지