spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false

  data:
    redis:
      host: j10b206.p.ssafy.io
      port: 6379
      # username :
      # pw

  datasource:
    jdbc-url: jdbc:postgresql://j10b206.p.ssafy.io:5432/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true

  thymeleaf:
    cache: false

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: false
#    #DB Table의 Column명과 변수명을 그대로 하고 싶을 때 사용하는 설정
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#  cloud:
#    aws:
#      s3:
#        bucket: sangchu-s3
#      #      folder:
#      #        [VARIABLE]: [VALUE]
#      credentials:
#        access-key: unknown
#        secret-key: unknown
#      region:
#        static: ap-northeast-2
#        auto: false
#      stack:
#        auto: false
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB

server:
  port: 8084 # 포트 충돌 방지