# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '상추 - 상권추천서비스' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'NMapsMap'

	# 네트워크 라이브러리
	pod 'Alamofire' , '5.1'
	# JSON	
	pod 'SwiftyJSON'
  # Pods for 상추 - 상권추천서비스

  target '상추 - 상권추천서비스Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '상추 - 상권추천서비스UITests' do
    # Pods for testing
  end

end

