services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
