version: '3.8'
services:
  app:
    image: sangchu-springboot-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
#    depends_on:
#      - redis
#      - postgres

#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=${POSTGRES_DB}'
#      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
#      - 'POSTGRES_USER=${POSTGRES_USER}'
#    ports:
#      - '${POSTGRES_PORT}:5432'
#    volumes:
#      - 'postgres_data:/var/lib/postgresql/data'
#
#  redis:
#    image: 'redis:latest'
#    command: redis-server --requirepass ${REDIS_PASSWORD}
#    ports:
#      - '${REDIS_PORT}:6379'
#    volumes:
#      - 'redis_data:/data'
#    healthcheck:
#      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "-a", "${REDIS_PASSWORD}", "ping" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5

#volumes:
#  redis_data:
#  postgres_data: