version: '3.8'
services:
  app:
    image: sangchu-springboot-app
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=test'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
#
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5
